### PR TITLE
Fix directory structure for Pontoon (localization)

### PR DESCRIPTION
**Pull request by sapohl**

### CODE REVIEW

**Comment by ghost** [comment]
As far as I can tell (which I'm not sure is very far, but still), the directory should be called "locale", not "locales".

**Comment by sapohl** [comment]
In-tree system addons generate a folder called "locales" after building, which hold all the locales. See bottom of https://bugzilla.mozilla.org/show_bug.cgi?id=1280378#c31. Is there another reason why you think this isn't named properly?

Edit: I _thought_ in-tree system addons generated a folder called "locales", but I can't seem to find proof of it anymore. I'd still prefer calling it "locales" though, as it will be holding more than one locale in our system addon.

**Comment by Standard8** [comment]
For the add-on itself, the chrome.manifest is the important pointer. Currently it says `locale`.

I don't know how Pontoon is configured to find the locales, but @mathjazz should be able to help.

**Comment by sapohl** [comment]
Oh, I forgot to update chrome.manifest. Fixed now.

**Comment by ghost** [comment]
All right, sounds good to me. I don't have write access to merge this or I would.

**Pull request merged**
